name: Test the Code

on: 
   workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}    
        
    env:
      DEVELOPER: "Aniket"
      BUILD_TYPE: "Practice Mode"
      DEPLOY: "Sachin"
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show OS
        run: echo "The code is running on OS :${{ matrix.os }}" tee -a run.log 
      - name: Build
        run: echo "Building the code" | tee -a run.log

      - name: Test
        run: echo "Testing the code by, $MY_NAME" | tee -a run.log
      
      - name: Deploy
        run: echo "Deployment of the code is done by, $DEPLOY" | tee -a run.log

      - name: Create Output file
        run: echo "This artifacts file is created by $DEVELOPER" | tee -a run.log

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: Logs-Files
          path: run.log
