name: Test the Code

on: 
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_NAME: "Aniket"
      BUILD_TYPE: "Practice Mode"
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: | 
          echo "This is build code."
          echo "My name is: $MY_NAME"
          echo "This code is build for: $BUILD_TYPE"
 
