name: Test the Code

on: 
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEVELOPER: "Aniket"
      BUILD_TYPE: "Practice Mode"
      DEPLOY: "Sachin"
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building the code"

      - name: Test
        run: echo "Testing the code by, $MY_NAME" > output.txt
      
      - name: Deploy
        run: echo "Deployment of the code is done by, $DEPLOY" > output.txt

      - name: Create Output file
        run: echo "This artifacts file is created by $DEVELOPER" > output.txt

      - name: Upload the file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-output-file
          path: output.txt
